networks:
  default:
    external: true
    name: n8n_default

services:
  nextjs:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SITE_URL=${SITE_URL:-https://kuhnisura.ru}
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=${SITE_URL:-https://kuhnisura.ru}
      - SITE_URL=${SITE_URL:-https://kuhnisura.ru}
    labels:
      - traefik.enable=true
      - traefik.http.routers.kuhnisura.rule=Host(`kuhnisura.ru`) || Host(`www.kuhnisura.ru`)
      - traefik.http.routers.kuhnisura.tls=true
      - traefik.http.routers.kuhnisura.entrypoints=web,websecure
      - traefik.http.routers.kuhnisura.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.kuhnisura.headers.SSLRedirect=true
      - traefik.http.middlewares.kuhnisura.headers.STSSeconds=315360000
      - traefik.http.middlewares.kuhnisura.headers.browserXSSFilter=true
      - traefik.http.middlewares.kuhnisura.headers.contentTypeNosniff=true
      - traefik.http.middlewares.kuhnisura.headers.forceSTSHeader=true
      - traefik.http.middlewares.kuhnisura.headers.SSLHost=kuhnisura.ru
      - traefik.http.middlewares.kuhnisura.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.kuhnisura.headers.STSPreload=true
      - traefik.http.routers.kuhnisura.middlewares=kuhnisura@docker
      - traefik.http.services.kuhnisura.loadbalancer.server.port=3000
    networks:
      - default
